"""create subscriptions schema

Revision ID: 22a28eed4966
Revises: 
Create Date: 2026-08-22 17:09:08.216218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22a28eed4966'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('service', sa.VARCHAR(length=32), nullable=False),
    sa.Column('category', postgresql.ENUM('essential', 'entertainment', 'school', name='category'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('billing_period', postgresql.ENUM('day', 'week', 'month', 'year', name='billing_period'), nullable=False),
    sa.Column('billing_interval', sa.SmallInteger(), nullable=False),
    sa.Column('payment_method', postgresql.ENUM('mBank MasterCard', 'mBank VISA', name='payment_method'), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.CheckConstraint('billing_interval > 0', name='billing_interval_is_positive'),
    sa.CheckConstraint('cost >= 0', name='cost_is_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
