"""add billing date offset

Revision ID: 5d2d65392650
Revises: 22a28eed4966
Create Date: 2026-08-23 16:15:36.386197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2d65392650'
down_revision = '22a28eed4966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_date_offset', sa.SmallInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('billing_date_offset')

    # ### end Alembic commands ###
