"""create subscriptions schema

Revision ID: 5fd5fc3d1d38
Revises:
Create Date: 2026-08-24 14:25:24.450097

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5fd5fc3d1d38"
down_revision: str | None = None
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("service", sa.VARCHAR(length=32), nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM("Essential", "Entertainment", "School", name="category"),
            server_default="Entertainment",
            nullable=False,
        ),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "start_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "billing_period",
            postgresql.ENUM("day", "week", "month", "year", name="billing_period"),
            server_default="month",
            nullable=False,
        ),
        sa.Column(
            "billing_interval",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column(
            "billing_date_offset",
            sa.SmallInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            postgresql.ENUM("mBank MasterCard", "mBank VISA", name="payment_method"),
            server_default="mBank MasterCard",
            nullable=False,
        ),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "active OR end_date IS NOT NULL", name="end_date_required_when_cancelled"
        ),
        sa.CheckConstraint("billing_interval > 0", name="billing_interval_is_positive"),
        sa.CheckConstraint("cost >= 0", name="cost_is_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("service"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
    bind = op.get_bind()
    postgresql.ENUM(
        name="payment_method",
    ).drop(bind, checkfirst=True)

    postgresql.ENUM(
        name="billing_period",
    ).drop(bind, checkfirst=True)

    postgresql.ENUM(
        name="category",
    ).drop(bind, checkfirst=True)
